nodeLinker: pnp

npmScopes:
  webaverse-studios:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

packageExtensions:
  '@tensorflow/tfjs@*':
    peerDependencies:
      seedrandom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-berry.cjs
