nodeLinker: node-modules

npmScopes:
  webaverse-studios:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

packageExtensions:
  '@feathershq/pinion@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@feathersjs/cli@*':
    peerDependencies:
      '@types/node': '*'
  '@feathersjs/generators@*':
    peerDependencies:
      '@types/node': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
