[package]
authors  = ["Jacob LeCoq <lecoqjacob@gmail.com>"]
edition  = "2021"
name     = "bevy-ecs-wasm"
resolver = "2"
version  = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
bevy     = "0.10"
bevy_ecs = "0.10"

anyhow   = "1"
tokio    = { version = "1", features = ["sync"] }
type-map = "0.5"

gloo-utils         = { version = "0.1", features = ["serde"] }
js-sys             = "0.3"
serde-wasm-bindgen = "0.5"
wasm-bindgen       = "0.2"
web-sys            = { version = "0.3", features = ["console"] }

serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc                = { version = "0.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
